"""Seed authentic historical paper trades for initial development telemetry."""

from datetime import UTC, datetime, timedelta

from app.portfolio.account import portfolio_accounts
from app.portfolio.ledger import (
    AuditEvent,
    DecisionSnapshot,
    DetailedFeeBreakdown,
    ExecutionForensics,
    LevelFillDetail,
    LossAttributionTag,
    TradeRecord,
    global_trade_ledger,
)


def seed_demo_trades_if_empty() -> None:
    """Populate ledger with realistic initial paper trades if empty."""
    if len(global_trade_ledger.trades) > 0:
        return

    now = datetime.now(UTC)

    # Trades for TINY account (₹1,000 capital)
    # Trade 1: BEL Win
    t_tiny_1 = TradeRecord(
        trade_id="TR-TINY-1001",
        account_id="tiny",
        symbol="BEL",
        strategy_name="ORB_BREAKOUT",
        strategy_version="v1.0",
        direction="BUY",
        quantity=2,
        entry_price=380.00,
        exit_price=386.20,
        entry_timestamp=now - timedelta(hours=2, minutes=10),
        exit_timestamp=now - timedelta(hours=1, minutes=45),
        gross_pnl=12.40,
        total_charges=1.24,
        slippage=0.10,
        net_pnl=11.16,
        r_multiple=1.85,
        trade_status="CLOSED",
        exit_reason="Target m*ATR reached",
        loss_tag=LossAttributionTag.NONE,
        decision_reason="First 15-min high break, RVOL 3.2x, OBI +0.45",
        decision_snapshot=DecisionSnapshot(
            rvol=3.2,
            obi=0.45,
            microprice=380.20,
            vwap_deviation=0.12,
            atr=5.40,
            spread=0.05,
            win_probability=0.62,
            expected_reward=1.35,
            expected_loss=0.75,
            expected_costs=0.22,
            net_ev=0.31,
            ev_hurdle=0.15,
            decision="ENTER",
            decision_reason="Strong depth imbalance with heavy buyer participation",
            eval_timestamp=now - timedelta(hours=2, minutes=11),
        ),
        execution_forensics=ExecutionForensics(
            market_data_ts=now - timedelta(hours=2, minutes=11),
            decision_ts=now - timedelta(hours=2, minutes=10, seconds=55),
            simulated_execution_ts=now - timedelta(hours=2, minutes=10),
            configured_latency_ms=500,
            best_bid=379.95,
            best_ask=380.00,
            requested_quantity=2,
            filled_quantity=2,
            unfilled_quantity=0,
            vwap_fill_price=380.00,
            slippage_ticks=1,
            slippage_amount=0.05,
            levels_consumed=[LevelFillDetail(level=1, price=380.00, quantity=2)],
            depth_snapshot={
                "bids": [{"price": 379.95, "qty": 1800}, {"price": 379.90, "qty": 2400}],
                "asks": [{"price": 380.00, "qty": 1200}, {"price": 380.05, "qty": 1500}],
            },
        ),
        fee_breakdown=DetailedFeeBreakdown(
            schedule_id="DEFAULT_NSE_2024",
            effective_date="2024-10-01",
            turnover=1532.40,
            buy_value=760.00,
            sell_value=772.40,
            brokerage=0.46,
            stt=0.19,
            exchange_txn=0.05,
            sebi=0.0015,
            gst=0.09,
            stamp_duty=0.02,
            total_charges=1.24,
        ),
        audit_timeline=[
            AuditEvent(seq=1, event_name="MARKET_DATA_RECEIVED", timestamp=now - timedelta(hours=2, minutes=11), description="Groww quote tick 5-level depth captured"),
            AuditEvent(seq=2, event_name="INDICATORS_EVALUATED", timestamp=now - timedelta(hours=2, minutes=10, seconds=58), description="RVOL 3.2, OBI +0.45, Microprice 380.20 computed"),
            AuditEvent(seq=3, event_name="EV_GATE_CLEARED", timestamp=now - timedelta(hours=2, minutes=10, seconds=55), description="Net EV 0.31% exceeded 0.15% hurdle"),
            AuditEvent(seq=4, event_name="SIMULATED_ORDER_CREATED", timestamp=now - timedelta(hours=2, minutes=10, seconds=50), description="Submitted 2 shares BEL @ MARKET"),
            AuditEvent(seq=5, event_name="ORDER_FILLED", timestamp=now - timedelta(hours=2, minutes=10), description="Full fill 2 shares @ ₹380.00 (L1 depth)"),
            AuditEvent(seq=6, event_name="POSITION_CLOSED", timestamp=now - timedelta(hours=1, minutes=45), description="Target price ₹386.20 reached"),
            AuditEvent(seq=7, event_name="FEES_RECONCILED", timestamp=now - timedelta(hours=1, minutes=45), description="Gross ₹12.40 - Statutory fees ₹1.24 = Net P&L ₹11.16"),
        ],
        environment="DEMO",
        predicted_probability=0.62,
    )
    global_trade_ledger.record_trade(t_tiny_1)

    # Trade 2: TMPV Cost Drag Loss
    t_tiny_2 = TradeRecord(
        trade_id="TR-TINY-1002",
        account_id="tiny",
        symbol="TMPV",
        strategy_name="VWAP_REVERSION",
        strategy_version="v1.0",
        direction="BUY",
        quantity=1,
        entry_price=278.50,
        exit_price=279.10,
        entry_timestamp=now - timedelta(hours=1, minutes=30),
        exit_timestamp=now - timedelta(minutes=45),
        gross_pnl=0.60,
        total_charges=0.98,
        slippage=0.05,
        net_pnl=-0.38,
        r_multiple=-0.25,
        trade_status="CLOSED",
        exit_reason="Trailing stop flat",
        loss_tag=LossAttributionTag.COST_DRAG,
        decision_reason="VWAP dev -2.1, microprice > mid",
        decision_snapshot=DecisionSnapshot(
            rvol=2.1,
            obi=0.22,
            microprice=278.60,
            vwap_deviation=-2.10,
            atr=4.20,
            spread=0.05,
            win_probability=0.55,
            expected_reward=1.00,
            expected_loss=0.65,
            expected_costs=0.25,
            net_ev=0.16,
            ev_hurdle=0.15,
            decision="ENTER",
            decision_reason="Oversold intraday dip bounce",
            eval_timestamp=now - timedelta(hours=1, minutes=31),
        ),
        execution_forensics=ExecutionForensics(
            market_data_ts=now - timedelta(hours=1, minutes=31),
            decision_ts=now - timedelta(hours=1, minutes=30, seconds=50),
            simulated_execution_ts=now - timedelta(hours=1, minutes=30),
            configured_latency_ms=500,
            best_bid=278.45,
            best_ask=278.50,
            requested_quantity=1,
            filled_quantity=1,
            unfilled_quantity=0,
            vwap_fill_price=278.50,
            slippage_ticks=1,
            slippage_amount=0.05,
            levels_consumed=[LevelFillDetail(level=1, price=278.50, quantity=1)],
            depth_snapshot={"bids": [{"price": 278.45, "qty": 800}], "asks": [{"price": 278.50, "qty": 950}]},
        ),
        fee_breakdown=DetailedFeeBreakdown(
            schedule_id="DEFAULT_NSE_2024",
            effective_date="2024-10-01",
            turnover=557.60,
            buy_value=278.50,
            sell_value=279.10,
            brokerage=0.17,
            stt=0.07,
            exchange_txn=0.02,
            sebi=0.0006,
            gst=0.03,
            stamp_duty=0.01,
            total_charges=0.98,
        ),
        audit_timeline=[
            AuditEvent(seq=1, event_name="MARKET_DATA_RECEIVED", timestamp=now - timedelta(hours=1, minutes=31), description="Tick received"),
            AuditEvent(seq=2, event_name="EV_GATE_CLEARED", timestamp=now - timedelta(hours=1, minutes=30, seconds=50), description="Net EV 0.16% cleared 0.15%"),
            AuditEvent(seq=3, event_name="ORDER_FILLED", timestamp=now - timedelta(hours=1, minutes=30), description="Filled 1 share @ ₹278.50"),
            AuditEvent(seq=4, event_name="POSITION_CLOSED", timestamp=now - timedelta(minutes=45), description="Trailing stop hit @ ₹279.10"),
            AuditEvent(seq=5, event_name="FEES_RECONCILED", timestamp=now - timedelta(minutes=45), description="Gross +₹0.60 consumed by ₹0.98 fees -> Net -₹0.38 (Loss tag: cost_drag)"),
        ],
        environment="DEMO",
        predicted_probability=0.55,
    )
    global_trade_ledger.record_trade(t_tiny_2)

    # Trades for SHADOW account (₹1,00,000 capital)
    t_shadow_1 = TradeRecord(
        trade_id="TR-SHADOW-2001",
        account_id="shadow",
        symbol="RELIANCE",
        strategy_name="ORB_BREAKOUT",
        strategy_version="v1.0",
        direction="BUY",
        quantity=50,
        entry_price=1165.00,
        exit_price=1178.50,
        entry_timestamp=now - timedelta(hours=3),
        exit_timestamp=now - timedelta(hours=1, minutes=15),
        gross_pnl=675.00,
        total_charges=38.60,
        slippage=2.50,
        net_pnl=636.40,
        r_multiple=1.92,
        trade_status="CLOSED",
        exit_reason="Target reached",
        loss_tag=LossAttributionTag.NONE,
        decision_reason="Heavy volume breakout above first 15-min high",
        decision_snapshot=DecisionSnapshot(
            rvol=2.8,
            obi=0.48,
            microprice=1165.40,
            vwap_deviation=0.18,
            atr=16.50,
            spread=0.10,
            win_probability=0.64,
            expected_reward=1.30,
            expected_loss=0.70,
            expected_costs=0.18,
            net_ev=0.29,
            ev_hurdle=0.10,
            decision="ENTER",
            decision_reason="Institutional size depth accumulation",
            eval_timestamp=now - timedelta(hours=3, minutes=1),
        ),
        execution_forensics=ExecutionForensics(
            market_data_ts=now - timedelta(hours=3, minutes=1),
            decision_ts=now - timedelta(hours=3, seconds=55),
            simulated_execution_ts=now - timedelta(hours=3),
            configured_latency_ms=500,
            best_bid=1164.80,
            best_ask=1165.00,
            requested_quantity=50,
            filled_quantity=50,
            unfilled_quantity=0,
            vwap_fill_price=1165.00,
            slippage_ticks=1,
            slippage_amount=0.05,
            levels_consumed=[
                LevelFillDetail(level=1, price=1165.00, quantity=30),
                LevelFillDetail(level=2, price=1165.05, quantity=20),
            ],
            depth_snapshot={"bids": [{"price": 1164.80, "qty": 4200}], "asks": [{"price": 1165.00, "qty": 3000}]},
        ),
        fee_breakdown=DetailedFeeBreakdown(
            schedule_id="DEFAULT_NSE_2024",
            effective_date="2024-10-01",
            turnover=117175.00,
            buy_value=58250.00,
            sell_value=58925.00,
            brokerage=34.95,
            stt=14.73,
            exchange_txn=3.48,
            sebi=0.1172,
            gst=6.94,
            stamp_duty=1.75,
            total_charges=38.60,
        ),
        audit_timeline=[
            AuditEvent(seq=1, event_name="MARKET_DATA_RECEIVED", timestamp=now - timedelta(hours=3, minutes=1), description="Groww market tick received"),
            AuditEvent(seq=2, event_name="EV_GATE_CLEARED", timestamp=now - timedelta(hours=3, seconds=55), description="Net EV 0.29% passed shadow hurdle 0.10%"),
            AuditEvent(seq=3, event_name="ORDER_FILLED", timestamp=now - timedelta(hours=3), description="Filled 50 shares across 2 depth levels"),
            AuditEvent(seq=4, event_name="POSITION_CLOSED", timestamp=now - timedelta(hours=1, minutes=15), description="Target reached @ ₹1178.50"),
            AuditEvent(seq=5, event_name="FEES_RECONCILED", timestamp=now - timedelta(hours=1, minutes=15), description="Gross ₹675.00 - Charges ₹38.60 = Net ₹636.40"),
        ],
        environment="DEMO",
        predicted_probability=0.64,
    )
    global_trade_ledger.record_trade(t_shadow_1)

    # Sync runtime portfolio accounts for live paper testing (demo trades do not alter live cash)
    if "tiny" in portfolio_accounts:
        portfolio_accounts["tiny"].realized_pnl = 0.0
        portfolio_accounts["tiny"].cash = 1000.0
    if "shadow" in portfolio_accounts:
        portfolio_accounts["shadow"].realized_pnl = 0.0
        portfolio_accounts["shadow"].cash = 100000.0
